### ISSUE TITLE
YCRCB + LUV + ETC [1]	1.33	0.00	0.00756	0.5954!  I find is not real

### ISSUE THREAD

**Issue by anthonyyuan** [ee09115/spoofing_detection#3]
hi:
   your job is good,but i find that real face do not be  detected  .   can u give some good pre model to test your job

**Comment by ee09115** [comment]
Hello,

You have opened your issue with the title "YCRCB + LUV + ETC [1] 1.33 0.00 0.00756 0.5954! I find is not real", and in your message you are asking me for some models. 

If you pay a closer look to the repository, I already have some models which give the results for the print-attack database, and replay-attack database. 

Have you tested the models on these databases? Are you getting different results on these databases?

If you are trying to use these models in other environments, you should take a look to this [issue](https://github.com/ee09115/spoofing_detection/issues/1)

Regards,
